### PR TITLE
fix(emoji-blast-site): correct zero-coords for hero button kbd click

### LINKED ISSUE #315: 🐛 Bug: when activated with the keyboard, emojis on the site originate from top left corner
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/emoji-blast/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

When I press the **Click Me** button with the keyboard, I'd expect emojis blast from the button's position (prolly centre of the button) 🤩💥💥

<p align="center">
Screenshot of the blast originating from the button's position
</p>

### Actual

Emojis blast from the top left corner of the page and this ain't so exciting when most of them end up beyond the visible area 😔⛈️

<p align="center">
Emojis are barely visible as they appear from the top left corner of the viewport
</p>

### Additional Info

<details><summary>Lies, lies everywhere 😡</summary>
<p>

The first two checkboxes in checklist aren't applicable but they're required: I didn't pull the repo, nor opened IDE 😏🐸

</p>
</details>

### PR DESCRIPTION
**Pull request by brawaru**
## PR Checklist

- [x] Addresses an existing open issue: fixes #315
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/emoji-blast/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/emoji-blast/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

This adds the correction for zero coordinates for when the hero button is clicked through the keyboard press (Enter key). There is no proper way to detect when the "click" MouseEvent is triggered by the keyboard, despite handling the zero coords, which also not always zero (Safari should set them to the center of the clicked element (for keyboard "clicks")).

### CODE REVIEW

File: packages/emoji-blast-site/src/components/hero/hero.tsx [hunk 1]
```diff
@@ -7,10 +7,29 @@ import { Anchor } from "../../components/anchor/anchor";
 import { Button } from "../button/button";
 import { Title } from "../title/title";
 import * as styles from "./styles";
+import { useCallback } from "react";
 
 export function Hero() {
 	useKonamiEmojiBlast();
 
+	const onExplosion = useCallback<React.MouseEventHandler<HTMLButtonElement>>(
+		(e) => {
```
Comment (JoshuaKGoldberg) [inline packages/emoji-blast-site/src/components/hero/hero.tsx:16]: The `Button` component is pretty straightforward and doesn't care about referential equality of its props properties. And `Hero` isn't going to re-render very often. I think adding `useCallback` is a bit of a premature optimization here.

I don't particularly mind having this be a new function vs. an inline one, but let's drop the `useCallback`. I.e.:

```suggestion
	const onExplosion = (e) => {
```


(that, but with types - however you prefer to declare it as a mouse event handler)

https://stackoverflow.com/questions/64134566/should-we-use-usecallback-in-every-function-handler-in-react-function-components

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Looks great, thanks for sending this so quickly ~after~ during the stream! 😄 

Just requesting changes on a bit of simplification, but I'm open to discussing if you feel strongly about it. Let me know!

File: packages/emoji-blast-site/src/components/hero/hero.tsx (hunk 1 above)
Comment (brawaru) [reply packages/emoji-blast-site/src/components/hero/hero.tsx]: Yeah, I kinda forgot that React doesn't actually attach listeners to the DOM elements for VNodes, like Preact and Solid would do, so swapping is so cheap that this optimisation doesn't make much sense indeed. I removed `useCallback`, but kept it as as a separate function with type definition so that that the JSX template below is easy to read at a glance 👍

**Review by JoshuaKGoldberg — APPROVED** [review]
Swell, thanks!

Someone on Ru Paul's Drag Race saying "That was so much better!"

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @brawaru for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙
